# Generated by Django 3.0.8 on 2020-07-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_movie_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('action', 'ACTION'), ('drama', 'DRAMA'), ('comedy', 'COMEDY'), ('romance', 'ROMANCE'), ('comedy', 'COMEDY'), ('sci-fi', 'SCI-FI'), ('horror', 'HORROR'), ('thriller', 'THRILLER'), ('mystery', 'MYSTERY'), ('crime', 'CRIME'), ('animation', 'ANIMATION'), ('adventure', 'ADVENTURE'), ('fantasy', 'FANTASY'), ('superhero', 'SUPERHERO')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('english', 'ENGLISH'), ('german', 'GERMAN'), ('hindi', 'HINDI'), ('spanish', 'SPANISH'), ('bengali', 'BENGALI'), ('telugu', 'TELUGU'), ('korean', 'KOREAN'), ('tamil', 'TAMIL')], max_length=10),
        ),
    ]
